#!/bin/sh
#
# (c) 2008, Simone Karin Lehmann, simone at lisanet dot de
# GPL version 2 or later
# script 1.3 Leo

DIR=`dirname "$0"`
cd "$DIR/../.."
APPDIR=`pwd`
cd - > /dev/null
# edit the next line to match version file
VERSION=2.6.12
LNDIR=/tmp/skl/Gimp.app
if [ ! -e "$LNDIR/Contents/Resources/v$VERSION" ]; then
	rm -f "$LNDIR"
	mkdir -p /tmp/skl
	chmod a+w /tmp/skl
	ln -s "$APPDIR" "$LNDIR"
fi

# update fonts cache from 2.6.1 to 2.6.2
# update-fc-cache
# setup gimp user directories
/Applications/Gimp.app/Contents/Resources/bin/setup-gimpdir
# setup help, for more information see bin/help-locale
rm -f /tmp/skl/Gimphelp
ln -s "$DIR/share/gimp/2.0/nohelp" /tmp/skl/Gimphelp
#/Applications/Gimp.app/Contents/Resources/bin/help-locale
# this only exists on Leopard, set font size
if [ -e "/tmp/skl/Gimp.app/Contents/Resources/bin/set-fontsize" ]; then
    /Applications/Gimp.app/Contents/Resources/bin/set-fontsize 
fi

cd ~/ > /dev/null
#exec "$CWD/bin/gimp" "$@"

DBUS=`/Applications/Gimp.app/Contents/Resources/bin/dbus-launch --sh-syntax`
eval $DBUS
echo $DBUS_SESSION_BUS_ADDRESS > /tmp/skl/dbus-address-$UID

/Applications/Gimp.app/Contents/Resources/bin/gimp-2.6 "$@"

rm /tmp/skl/dbus-address-$UID
kill $DBUS_SESSION_BUS_PID
